FROM ruby:4.0.1

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
ENV RAILS_ENV=production

RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

# image_processing 用
RUN apt-get update -qq && apt-get install -y libvips

# Deal with Bundler bugs
RUN gem update --system

RUN bundle install

COPY . /myapp
RUN mkdir -p tmp/sockets
RUN mkdir -p tmp/pids

VOLUME /myapp/public
VOLUME /myapp/tmp

# Add a script to be executed every time the container starts.
COPY entrypoint.prod.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.prod.sh
ENTRYPOINT ["entrypoint.prod.sh"]
EXPOSE 3000