source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "4.0.1"

# レスポンスJSONを制御する
gem "active_model_serializers"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# 環境毎の設定管理を行う
gem "config"

# ユーザー認証を提供する
gem "devise"

# devise を日本語化する
gem "devise-i18n"

# ユーザーのトークン認証を提供する
gem "devise_token_auth"

# ページネーション機能を提供する
gem "kaminari"

# enum を日本語化する
gem "enum_help"

# MySQLに接続する
gem "mysql2", "~> 0.5.7"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 6.4"

# cors 設定を管理する
gem "rack-cors"

# rails本体（標準gem）
gem "rails", "~> 8.1.2"

# メッセージを日本語化
gem "rails-i18n"

group :development, :test do
  # テスト用のデータを作成する
  gem "factory_bot_rails"
  gem "faker"

  # 開発環境でメール送信をテストする
  gem "letter_opener_web"

  # pry コンソールを使えるようにする
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # テストフレームワーク rspec を導入する
  gem "rspec-rails"

  # rubocop を使えるようにする
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
